services:
  app:
    build: .
    container_name: python_app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=p26
      - POSTGRES_HOST=postgres_service
      - POSTGRES_PORT=5432
    depends_on:
      - postgres_service
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=p26
    ports:
      - "5432:5432"
    volumes:
      - new_pg_data:/var/lib/postgresql/data

volumes:
  new_pg_data:
